name: Validation

on:
  push:
    branches: [ $default-branch ]

jobs:
  validate:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 15
      uses: actions/setup-node@v1
      with:
        node-version: "15"
    - name: Use yarn 2
      run: yarn set version berry
    - name: Validate
      run: yarn dlx --quiet js-org-validate
    - name: Annotate
      uses: yuzutech/annotations-action@v0.1.0
      if:  github.event_name == 'push'
      with:
        repo-token: "${{ secrets.GITHUB_TOKEN }}"
        input: './annotations.json'
    - name: 'Comment PR'
      uses: actions/github-script@0.3.0
      if: github.event_name == 'pull_request'
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const { issue: { number: issue_number }, repo: { owner, repo }  } = context;
          github.issues.createComment({ issue_number, owner, repo, body: 'Hello world ! 👋' });
