name: Validation

on:
    push:
        branches: [master]
    pull_request:
        branches: [master]

jobs:
    validate:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Use Node.js 15
              uses: actions/setup-node@v1
              with:
                  node-version: "15"
            - name: Use yarn 2
              run: yarn set version berry
            - name: Validate
              run: yarn dlx --quiet js-org-validate
            - name: Annotate
              uses: yuzutech/annotations-action@v0.1.0
              if: always() && github.event_name == 'push'
              with:
                  repo-token: "${{ secrets.GITHUB_TOKEN }}"
                  input: "./annotations.json"
            - id: get_pr_comment
              name: Get PR comment
              if: always() && github.event_name == 'pull_request'
              run: |
                  content=`cat ./comment.md`
                  echo "::set-output name=comment::$content"
            - name: Comment PR
              uses: unsplash/comment-on-pr@master
              if: always() && github.event_name == 'pull_request'
              env:
                  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
              with:
                  msg: ${{steps.get_pr_comment.outputs.comment}}
                  check_for_duplicate_msg: false
